databases:
  - name: wallee-production
    databaseName: wallee
    plan: free
    region: frankfurt
    user: wallee

services:
  - type: web
    name: wallee-api
    plan: free
    region: frankfurt
    rootDir: api
    runtime: ruby
    buildCommand: "./bin/render"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wallee-production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
