services:
  - type: web
    name: wallee-api
    plan: free
    region: frankfurt
    rootDir: api
    runtime: ruby
    buildCommand: "./bin/render"
    startCommand: "bundle exec rails server"
    envVars:
      - key: CLIENT_URL
        value: https://wallee-client.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
