source "https://rubygems.org"

ruby "3.3.1"

# Reduces boot times through caching; required in config/boot.rb
# [https://github.com/Shopify/bootsnap]
gem "bootsnap", "~> 1.18.3", require: false # Installed by default with rails 7.1.3.2

# A flexible authentication solution for Rails based on Warden
# [https://github.com/heartcombo/devise]
gem "devise", "~> 4.9.4"

# A Devise extension which uses JWT tokens for user authentication
# [https://github.com/waiting-for-dev/devise-jwt]
gem "devise-jwt", "~> 0.11.0"

# Multithreaded, Postgres-based, Active Job backend for Ruby on Rails.
# [https://github.com/bensheldon/good_job]
gem "good_job", "~> 4.9.0"

# The ruby interface for PostgreSQL
# [https://github.com/ged/ruby-pg]
gem "pg", "~> 1.5.6"

# A Ruby/Rack web server built for parallelism
# [https://github.com/puma/puma]
gem "puma", "~> 6.4.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# [https://github.com/cyu/rack-cors]
gem "rack-cors", "~> 2.0.2"

# A web-application framework that includes everything needed to create database-backed web applications
# [https://github.com/rails/rails]
gem "rails", "~> 7.1.3.2"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# [https://github.com/tzinfo/tzinfo-data]
gem "tzinfo-data", "~> 2.0.6", platforms: %i[windows jruby] # Installed by default with rails 7.1.3.2

group :development do
  # Make your Rubies go faster with this command line tool highly inspired by fast-ruby
  # [https://github.com/DamirSvrtan/fasterer]
  gem "fasterer", "~> 0.11.0"

  # An extension to RuboCop focused on Performance optimization analysis
  # [https://github.com/rubocop/rubocop-performance]
  gem "rubocop-performance", "~> 1.20.2", require: false

  # A RuboCop extension focused on enforcing Rails best practices and coding conventions
  # [https://github.com/rubocop/rubocop-rails]
  gem "rubocop-rails", "~> 2.24.1", require: false

  # An extension to RuboCop focused on RSpec-specific analysis
  # [https://github.com/rubocop/rubocop-rspec]
  gem "rubocop-rspec", "~> 2.29.2", require: false

  # A linter & formatter built on RuboCop that brings the ethos of StandardJS to Ruby
  # [https://github.com/standardrb/standard]
  gem "standard", "~> 1.35.1"
end

group :development, :test do
  # A Ruby gem to load environment variables from `.env`.
  # [https://github.com/bkeepers/dotenv]
  gem "dotenv", "~> 3.1.2"

  # Rails integration of factory_bot, a fixtures replacement with a straightforward definition syntax
  # [https://github.com/thoughtbot/factory_bot_rails]
  gem "factory_bot_rails", "~> 6.4.3"

  # Step-by-step debugging and stack navigation in Pry
  # [https://github.com/deivid-rodriguez/pry-byebug]
  gem "pry-byebug", "~> 3.10.1"

  # Rails integration of rspec, a testing framework to replace Rails' minitest
  # [https://github.com/rspec/rspec-rails]
  gem "rspec-rails", "~> 6.1.2"

  # Code coverage for Ruby with a powerful configuration library and automatic merging of coverage across test suites
  # [https://github.com/simplecov-ruby/simplecov]
  gem "simplecov", "~> 0.22.0"
end
